name: Frontend Login Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-login-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start app
        run: npm run preview &
        # hoặc npm start / npm run dev &

      - name: Wait for app
        run: npx wait-on http://localhost:3000
        # đổi port cho đúng project của bạn

      - name: Run Cypress Login Tests
        run: npx cypress run --browser chrome        